### ISSUE TITLE
Error: You should create pull-point subscription first!

### ISSUE THREAD

**Issue by juan11perez** [dmitrif/onvif2mqtt#13]
first, thank you for this component.
trying to use with DS-KB6003-WIP (https://www.hikvision.com/en/products/Video-Intercom-Products/Doorbells/Value-Series/DS-KB6003-WIP/)

its connecting to mqtt and seems to connect to the doorbell but then it exits with the above error. See below docker logs

```
{"level":30,"time":1593969526432,"msg":"Validating configuration file.","v":1}
{"level":30,"time":1593969526480,"name":"Manager","msg":"Beginning initialization...","v":1}
{"level":30,"time":1593969526480,"name":"MQTT","hostname":"192.168.1.100:1883","msg":"Connecting.","v":1}
{"level":30,"time":1593969526505,"name":"MQTT","hostname":"192.168.1.100:1883","msg":"Successfully connected.","v":1}
{"level":30,"time":1593969526505,"name":"ONVIF/frontdoor","hostname":"192.168.1.17","msg":"Attempting connection.","v":1}
{"level":20,"time":1593969526506,"name":"MQTT","hostname":"192.168.1.100:1883","msg":"Publishing. {\"topic\":\"onvif2mqtt/frontdoor/motion\",\"value\":\"OFF\",\"retain\":true}","v":1}
{"level":30,"time":1593969526694,"name":"ONVIF/frontdoor","hostname":"192.168.1.17","msg":"Successfully connected.","v":1}

/onvif2mqtt/node_modules/onvif/lib/events.js:139
			throw new Error('You should create pull-point subscription first!');
			^
Error: You should create pull-point subscription first!
    at Cam.pullMessages (/onvif2mqtt/node_modules/onvif/lib/events.js:139:10)
    at Cam._eventPull (/onvif2mqtt/node_modules/onvif/lib/events.js:262:9)
    at Cam.<anonymous> (/onvif2mqtt/node_modules/onvif/lib/events.js:100:13)
    at parseSOAPString (/onvif2mqtt/node_modules/onvif/lib/utils.js:98:3)
    at IncomingMessage.<anonymous> (/onvif2mqtt/node_modules/onvif/lib/cam.js:214:4)
    at IncomingMessage.emit (events.js:323:22)
    at endReadableNT (_stream_readable.js:1204:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! onvif-cam@1.0.4 start: `node dist/index.js`
npm ERR! Exit status 1

npm ERR! Failed at the onvif-cam@1.0.4 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-07-05T17_18_46_719Z-debug.log
> onvif-cam@1.0.4 start /onvif2mqtt
> node dist/index.js
```

**Comment by dmitrif** [comment]
Hi! I have seen this issue before with firmwares / hardware that does not support a true ONVIF subscription. Is there any alternative firmware that this device can be tested with?

Thanks!

**Comment by juan11perez** [comment]
@dmitrif  thank you for your response. I used omvifier apk and it can recognise this doorbell.
I'm not aware of any replacement firmware.

**Comment by dmitrif** [comment]
Thanks, @juan11perez . Unfortunately since I do have access to the hardware to test it out, I am not able to resolve this. If someone has access to the device, I highly encourage this as a first-issue.

**Comment by ksupipr** [comment]
Create pull request https://github.com/dmitrif/onvif2mqtt/pull/21

**Comment by dmitrif** [comment]
Resolved on latest. Please reopen if issue persists
