### ISSUE TITLE
config.yml location

### ISSUE THREAD

**Issue by fate8383** [dmitrif/onvif2mqtt#47]
Hi, I am getting below error, i cannot find out where to put this config.yml file. I have config.dev.yml and it is working. I am running baremetal on RPI3b.

npm run dev - works perfectly fine - getting motion on HomeKit all good

I think I have to run the below production one to be able to run this on startup, which i would appreciate if you can also tell me how to run this on each reboot automatically and without debug mode.

So the issue is like below:

npm run build - also compiles successfully but following below command returns following error
CONFIG_FILE=./config.dev.yml npm run start

> onvif-cam@1.0.4 start
> node dist/index.js

{"level":30,"time":1635326028505,"msg":"Loading configuration. {\"configPath\":\"/config/config.yml\"}","v":1}
node:internal/fs/utils:344
    throw err;
    ^

Error: ENOENT: no such file or directory, open '/config/config.yml'
    at Object.openSync (node:fs:585:3)
    at Object.readFileSync (node:fs:453:35)
    at Config._loadUserConfig (/home/pi/onvif2mqtt/dist/Config.js:63:40)
    at Config._loadConfig (/home/pi/onvif2mqtt/dist/Config.js:106:28)
    at new Config (/home/pi/onvif2mqtt/dist/Config.js:145:23)
    at new Manager (/home/pi/onvif2mqtt/dist/Manager.js:207:17)
    at Object.<anonymous> (/home/pi/onvif2mqtt/dist/index.js:7:1)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/config/config.yml'
}

**Comment by cicciovo** [comment]
How?

**Comment by fate8383** [comment]
> How?

well it is not very easy i have to say :) I created a script and a service to run this. but just to test use this
CONFIG_FILE=./config.dev.yml npm run start (wrong)
CONFIG_PATH=./config.dev.yml npm run start (correct)
