### ISSUE TITLE
Config probelm 

### ISSUE THREAD

**Issue by cicciovo** [dmitrif/onvif2mqtt#49]
Hi, i can try To start onvif2mqtt but when i do the command: 
CONFIG_PATH=/home/pi/onvif2mqtt/default-config.yml npm run start
I have this log:
> onvif-cam@1.0.4 start
> node dist/index.js

{"level":30,"time":1639595095591,"msg":"Loading configuration. {\"configPath\":\"/home/pi/onvif2mqtt/default-config.yml\"}","v":1}
{"level":30,"time":1639595095620,"msg":"Validating configuration file.","v":1}
{"level":50,"time":1639595095628,"msg":"Config validation failed...","v":1}
{"level":50,"time":1639595095629,"msg":"log must be one of [trace,debug,info,warn,error,fatal] {\"path\":\"log\"}","v":1}

my default-config.yml is this:

mqtt:
 host: 127.0.0.1
 port: 1883
onvif:
 - name: Videocamera
hostname: 192.168.1.10
port: 2020
username: xxx
password: xxx

how i can fix it? 
I’m in raspberry..

**Comment by cicciovo** [comment]
If i delete the tre space before hostname etc i obtain this:

 onvif-cam@1.0.4 start
> node dist/index.js

/home/pi/onvif2mqtt/node_modules/yaml/dist/index.js:81
  if (doc.errors.length > 0) throw doc.errors[0];
                             ^

YAMLSyntaxError: Document is not valid YAML (bad indentation?)
    at /home/pi/onvif2mqtt/node_modules/yaml/dist/Document.js:228:28
    at Array.forEach (<anonymous>)
    at Document.parseContents (/home/pi/onvif2mqtt/node_modules/yaml/dist/Document.js:224:14)
    at Document.parse (/home/pi/onvif2mqtt/node_modules/yaml/dist/Document.js:157:10)
    at parseDocument (/home/pi/onvif2mqtt/node_modules/yaml/dist/index.js:68:37)
    at Object.parse (/home/pi/onvif2mqtt/node_modules/yaml/dist/index.js:79:15)
    at Config._loadDefaultConfig (/home/pi/onvif2mqtt/dist/Config.js:56:29)
    at Config._loadConfig (/home/pi/onvif2mqtt/dist/Config.js:104:31)
    at new Config (/home/pi/onvif2mqtt/dist/Config.js:145:23)
    at new Manager (/home/pi/onvif2mqtt/dist/Manager.js:207:17) {
  source: Collection {
    error: null,
    range: Range { start: 94, end: 117 },
    valueRange: Range { start: 94, end: 116 },
    props: [],
    type: 'MAP',
    value: null,
    items: [
      <ref *1> PlainValue {
        error: YAMLSyntaxError: Block collection must not have preceding content here (e.g. directives-end indicator)
            at /home/pi/onvif2mqtt/node_modules/yaml/dist/cst/ParseContext.js:152:24
            at Document.parseContents (/home/pi/onvif2mqtt/node_modules/yaml/dist/cst/Document.js:181:26)
            at Document.parse (/home/pi/onvif2mqtt/node_modules/yaml/dist/cst/Document.js:244:19)
            at parse (/home/pi/onvif2mqtt/node_modules/yaml/dist/cst/parse.js:33:18)
            at parseDocument (/home/pi/onvif2mqtt/node_modules/yaml/dist/index.js:67:34)
            at Object.parse (/home/pi/onvif2mqtt/node_modules/yaml/dist/index.js:79:15)
            at Config._loadDefaultConfig (/home/pi/onvif2mqtt/dist/Config.js:56:29)
            at Config._loadConfig (/home/pi/onvif2mqtt/dist/Config.js:104:31)
            at new Config (/home/pi/onvif2mqtt/dist/Config.js:145:23)
            at new Manager (/home/pi/onvif2mqtt/dist/Manager.js:207:17) {
          source: [Circular *1]
        },
        range: Range { start: 94, end: 102 },
        valueRange: Range { start: 94, end: 102 },
        props: [],
        type: 'PLAIN',
        value: null,
        resolved: Scalar { value: 'hostname', range: [ 94, 102 ], type: 'PLAIN' }
      },
      CollectionItem {
        error: null,
        range: Range { start: 102, end: 116 },
        valueRange: Range { start: 102, end: 116 },        props: [],
        type: 'MAP_VALUE',
        value: null,
        node: null
      }
    ],
    resolved: YAMLMap {
      items: [
        Pair {
          key: Scalar { value: 'hostname', range: [Array], type: 'PLAIN' },
          value: null,
          type: 'PAIR'
        }
      ],
      schema: undefined,
      range: [ 94, 117 ],
      type: 'MAP'
    }
  }
}

**Comment by cicciovo** [comment]
log: debug solve my problem 😅
